### ISSUE TITLE
Error creating a PyPy3.3 virtualenv

### ISSUE THREAD

**Issue by brechtm** [pyenv/pyenv-virtualenv#188]
```
[12:37:36] (15) /tmp
$ pyenv install pypy3.3-5.2-alpha1
Installing pypy3.3-v5.2.0-alpha1-osx64...
Installed pypy3.3-v5.2.0-alpha1-osx64 to /Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1

[12:37:58] (22) /tmp
$ pyenv virtualenv pypy3.3-5.2-alpha1 rinoh_pypy3
Collecting virtualenv
  Using cached virtualenv-15.0.3-py2.py3-none-any.whl
Installing collected packages: virtualenv
Successfully installed virtualenv-15.0.3
Using base prefix '/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1'
New pypy executable in /Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/envs/rinoh_pypy3/bin/python
Also creating executable in /Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/envs/rinoh_pypy3/bin/pypy
Installing setuptools, pip, wheel...
  Complete output from command /Users/brechtm/.pyen...noh_pypy3/bin/python - setuptools pip wheel:
  Collecting setuptools
  Using cached setuptools-25.1.6-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 620, in _prepare_file
    dist = abstract_dist.dist(finder)
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 108, in dist
    self.req_to_install.source_dir))[0]
IndexError: list index out of range
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /Users/brechtm/.pyen...noh_pypy3/bin/python - setuptools pip wheel failed with error code 2
Ignoring indexes: https://pypi.python.org/simple
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-8.1.2 setuptools-21.2.1
```
##

**Comment by brechtm** [comment]
Possibly related: pypa/pip#3625

**Comment by brechtm** [comment]
I seem to remember this used to work. Perhaps this is caused by a new version of setuptools/pip/virtualenv?

**Comment by brechtm** [comment]
I managed to "fix" the issue by removing/renaming the `pip-8.0.2-py2.py3-none-any.whl` inside `/Users/brechtm/.pyenv/versions/pypy3.3-5.2-alpha1/site-packages/virtualenv_support/` which crashes under PyPy3. There's also `pip-8.1.2-py2.py3-none-any.whl`, so I suppose that one is now being used.

**Comment by tarkatronic** [comment]
This same thing "fixed" it for me, thanks! But, as an extra twist, the wheel I needed to delete was not nearly as simple to find, because of my use case.

Specifically, I'm running tox from inside a virtualenv, so the wheel I needed to delete was located at: `~/.virtualenvs/django-requestlogging/lib/python3.5/site-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl`

**Comment by hroncok** [comment]
Also happens with pypy3 5.5.0

**Comment by urishalit** [comment]
As @hroncok stated happens on pypy3 5.5.0

Is there any workaround?
Pasting the error here:

```
virtualenv envp3 -p pypy3-v5.5.0-linux64/bin/pypy3                                                                                           2017-01-31 08:22:39
Running virtualenv with interpreter pypy3-v5.5.0-linux64/bin/pypy3
Using base prefix '/home/uri/src/pypy3-v5.5.0-linux64'
New pypy executable in /home/uri/src/envp3/bin/pypy3
Not overwriting existing pypy script /home/uri/src/envp3/bin/pypy (you must use /home/uri/src/envp3/bin/pypy3)
Installing setuptools, pip, wheel...
  Complete output from command /home/uri/src/envp3/bin/pypy3 - setuptools pip wheel:
  Collecting setuptools
  Using cached setuptools-34.1.0-py2.py3-none-any.whl
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/basecommand.py", line 209, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/commands/install.py", line 299, in run
    requirement_set.prepare_files(finder)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 359, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 620, in _prepare_file
    dist = abstract_dist.dist(finder)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv_support/pip-8.0.2-py2.py3-none-any.whl/pip/req/req_set.py", line 108, in dist
    self.req_to_install.source_dir))[0]
IndexError: list index out of range
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 2327, in <module>
    main()
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 711, in main
    symlink=options.symlink)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 944, in create_environment
    download=download,
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 900, in install_wheel
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=SCRIPT)
  File "/usr/local/lib/python2.7/dist-packages/virtualenv.py", line 795, in call_subprocess
    % (cmd_desc, proc.returncode))
OSError: Command /home/uri/src/envp3/bin/pypy3 - setuptools pip wheel failed with error code 2
```
