### ISSUE TITLE
Package install with pip in 3.6.4 virtualenv not available in python 3.6.4

### ISSUE THREAD

**Issue by edouardp** [pyenv/pyenv-virtualenv#252]
Perhaps I'm doing something wrong here, but I installed pyenv and pyenv-virtualenv via the instructions  from their respective github README.md files, and then set up a directory to use later with jupyter:

```$ pyenv install 3.6.4
$ pyenv virtualenv 3.6.4 crypto
$ mkdir crypto
$ cd crypto
$ pyenv local crypto```

but then I can't `import Crypto` from python 3.6.4 in that directory

```$ pwd
/home/edouard/py/crypto
$ pyenv version
crypto (set by /home/edouard/py/crypto/.python-version)
$ which python
/home/edouard/.pyenv/shims/python
$ which python3
/home/edouard/.pyenv/shims/python3
$ pip install Crypto
Requirement already satisfied: Crypto in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages
Requirement already satisfied: Naked in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Crypto)
Requirement already satisfied: shellescape in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Crypto)
Requirement already satisfied: pyyaml in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Naked->Crypto)
Requirement already satisfied: requests in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Naked->Crypto)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
Requirement already satisfied: certifi>=2017.4.17 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
Requirement already satisfied: idna<2.7,>=2.5 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
$ python3
Python 3.6.4 (default, Mar 15 2018, 21:23:40) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'```

but, and I don't understand this, if I run `python`, then it runs my system version, and I can import `Crypto`

```$ python
Python 2.7.14 (default, Sep 23 2017, 22:06:14) 
[GCC 7.2.0] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto
>>> Crypto.__version__
'2.6.1'```

I though perhaps I needed to run pip3, but running that now at least gives me the same result

```$ pip3 install Crypto
Requirement already satisfied: Crypto in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages
Requirement already satisfied: shellescape in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Crypto)
Requirement already satisfied: Naked in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Crypto)
Requirement already satisfied: requests in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Naked->Crypto)
Requirement already satisfied: pyyaml in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from Naked->Crypto)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
Requirement already satisfied: certifi>=2017.4.17 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
Requirement already satisfied: idna<2.7,>=2.5 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
Requirement already satisfied: urllib3<1.23,>=1.21.1 in /home/edouard/.pyenv/versions/3.6.4/envs/crypto/lib/python3.6/site-packages (from requests->Naked->Crypto)
$ python3
Python 3.6.4 (default, Mar 15 2018, 21:23:40) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'```

**Comment by edouardp** [comment]
I also tried an explicit `pyenv activate crypto`, but same result again
```
$ pyenv activate crypto
pyenv-virtualenv: prompt changing will be removed from future release. configure `export PYENV_VIRTUALENV_DISABLE_PROMPT=1' to simulate the behavior.
(crypto) $ python3
Python 3.6.4 (default, Mar 15 2018, 21:23:40) 
[GCC 7.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import Crypto
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'Crypto'
```
