### ISSUE TITLE
mkvirtualenv / penv virtualenv version name doesn't seem to work

### ISSUE THREAD

**Issue by velis74** [pyenv/pyenv-virtualenv#311]
Just installed pyenv to my lxqt ubuntu 18.04 using installer. Added virtualenvwrapper as a plugin too. Then I installed 4 python versions.

`$ pyenv versions`:
```
  system
* 3.1.5 (set by PYENV_VERSION environment variable)
  3.3.7
  3.5.6
  3.7.2
```

`mkvirtualenv test`:
```
Using base prefix '/usr'
New python executable in /home/jure/.virtualenvs/test/bin/python3
Also creating executable in /home/jure/.virtualenvs/test/bin/python
Installing setuptools, pip, wheel...
done.
```

`deactivate`

`mkvirtualenv -p python3.1 test3.1` or `pyenv virtualenv 3.1.5 test3.1`:

```
New python executable in /home/jure/.pyenv/versions/3.1.5/envs/test3.1/bin/python3.1
Also creating executable in /home/jure/.pyenv/versions/3.1.5/envs/test3.1/bin/python
Command /home/jure/.pyenv/ve...est3.1/bin/python3.1 -m pip config list had error code 255
Installing setuptools, pip, wheel...

  Complete output from command /home/jure/.pyenv/ve...est3.1/bin/python3.1 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 8, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 19, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.0.3-py2.py3-none-any.whl/pip/_internal/locations.py", line 9, in <module>
ImportError: No module named sysconfig
```

I have found this [SO question](https://stackoverflow.com/questions/28011865/why-cant-my-virtualenv-find-distutils-sysconfig), but it doesn't help me.

What am I doing wrong?

**Comment by velis74** [comment]
Updating this with my current attempt on ubuntu 14.04 LTS. Again, clean install of `pyenv` + adding the `pyenv-virtualenvwrapper`.
Successfully installed pythons:
```
$ pyenv versions
  system
  3.1.5
  3.3.7
* 3.5.7 (set by /home/jure/.pyenv/version)
```

Adding virtualenv for python 3.5:
```
$ mkvirtualenv test3.5
Using base prefix '/home/jure/.pyenv/versions/3.5.7'
New python executable in /home/jure/.virtualenvs/test3.5/bin/python3.5
Also creating executable in /home/jure/.virtualenvs/test3.5/bin/python
Installing setuptools, pip, wheel...
done.
virtualenvwrapper.user_scripts creating /home/jure/.virtualenvs/test3.5/bin/predeactivate
virtualenvwrapper.user_scripts creating /home/jure/.virtualenvs/test3.5/bin/postdeactivate
virtualenvwrapper.user_scripts creating /home/jure/.virtualenvs/test3.5/bin/preactivate
virtualenvwrapper.user_scripts creating /home/jure/.virtualenvs/test3.5/bin/postactivate
virtualenvwrapper.user_scripts creating /home/jure/.virtualenvs/test3.5/bin/get_env_details
```

Adding virtualenv for python 3.1:
```
$ pyenv global 3.1.5 
$ mkvirtualenv test3.1
New python executable in /home/jure/.virtualenvs/test3.1/bin/python3.1
Also creating executable in /home/jure/.virtualenvs/test3.1/bin/python
Command /home/jure/.virtualenvs/test3.1/bin/python3.1 -m pip config list had error code 255
Installing setuptools, pip, wheel...

  Complete output from command /home/jure/.virtualenvs/test3.1/bin/python3.1 - setuptools pip wheel:
  Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/__init__.py", line 40, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/autocompletion.py", line 8, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/main_parser.py", line 8, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/cli/cmdoptions.py", line 19, in <module>
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv_support/pip-19.1.1-py2.py3-none-any.whl/pip/_internal/locations.py", line 9, in <module>
ImportError: No module named sysconfig

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
ImportError: cannot import name main
----------------------------------------
...Installing setuptools, pip, wheel...done.
Traceback (most recent call last):
  File "/home/jure/.pyenv/versions/3.1.5/bin/virtualenv", line 11, in <module>
    sys.exit(main())
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv.py", line 831, in main
    symlink=options.symlink,
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv.py", line 1123, in create_environment
    install_wheel(to_install, py_executable, search_dirs, download=download)
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv.py", line 973, in install_wheel
    _install_wheel_with_search_dir(download, project_names, py_executable, search_dirs)
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv.py", line 1060, in _install_wheel_with_search_dir
    call_subprocess(cmd, show_stdout=False, extra_env=env, stdin=script)
  File "/home/jure/.pyenv/versions/3.1.5/lib/python3.1/site-packages/virtualenv.py", line 924, in call_subprocess
    raise OSError("Command {} failed with error code {}".format(cmd_desc, proc.returncode))
OSError: Command /home/jure/.virtualenvs/test3.1/bin/python3.1 - setuptools pip wheel failed with error code 1
```

My guess is that pip simply no longer supports python3.1 in its latest versions, but pyenv tries to install latest pip version regardless.

I believe this could be classified as pyenv bug?

**Comment by yyuu** [comment]
I don't think everything should work against the platform which has already been EOL'ed. In general you should take care of yourself if you have some reason to live with the platform where the clock has already stopped. So, I will close this as not an issue. I am still open to accept some workaround code that helps ancient versions spinning, though.

pyenv-virtualenv has some adhoc code to install specific version of virtualenv per Pytjon versions. Apparently it wsn't working well for 3.1, as upstream virtualenv cut off the support for the ancient python. 

https://github.com/pyenv/pyenv-virtualenv/blob/v1.1.5/bin/pyenv-virtualenv#L395

pyenv-virtuenv is offering some hook point to insta some custom set of virtualenv/pip/seruptools versions. I do not know what version works for 3.1 though.

https://github.com/pyenv/pyenv-virtualenv/blob/v1.1.5/bin/pyenv-virtualenv#L195

**Comment by velis74** [comment]
@yyuu You completely misunderstood the point: I ONLY installed 14.04 because I thought I would have fewer issues with installing older python versions. You can see that OP has 18.04, but the problems reported are the same.

Anyway, I'm suffering from a similar issue with python 3.3 as well - with it wheel complains that it doesn't support 3.3... 

Not sure how to proceed from here: defaults don't seem to work, regardless of how old my ubuntu base system I use. The problems I'm suffering aren't listed in FAQs, so I thought help would be easy to find. I am yet to successfully build a virtualenv with a working python other than the one that comes with the OS.

I thought this was exactly what pyenv was supposed to be for.
