### ISSUE TITLE
Pyenv virtualenv no longer shims pip

### ISSUE THREAD

**Issue by alexhalford** [pyenv/pyenv-virtualenv#325]
I have been using (Homebrew) pyenv and pyenv-virtualenv for a long time, and my usual procedure for creating a virtual environment (with 3.7.4, for example) is:

```
pyenv install 3.7.4
pyenv virtualenv 3.7.4 foo
pyenv activate foo
```

This works fine, and running `which python` gives:
`/Users/bar/.pyenv/shims/python`
And `python --version` gives:
`Python 3.7.4`
as expected. 

However, doing the same for pip gives:
`/usr/local/bin/pip`
i.e., the system pip. This also means that `pip install`ing anything installs it to the system python, not to the virtualenv (packages are not subsequently available in the virtualenv, e.g. `pip install django`, followed by running a python django app, complains that there is no django installed)

This suggests that there is no shim for pip, which is weird, because this has always worked for me in the past. I have tried uninstalling both pyenv and pyenv-virtualenv, deleting .pyenv, and reinstalling them, but it made no difference.

**Comment by jameslombard** [comment]
I'm having the same problem. Any updates on this issue?

**Comment by jameslombard** [comment]
Also, when I work straight from the installed version for the virtualenv, ie 3.6.0, the `pyenv which pip` command gives the expected output:
`/home/james/.pyenv/versions/3.6.0/bin/pip`
But when I try to inspect the dependencies ie. `pip freeze`, I get the following error:
```Traceback (most recent call last):
  File "/home/james/.pyenv/versions/3.6.0/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/__init__.py", line 233, in main
    return command.main(cmd_args)
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/basecommand.py", line 251, in main
    timeout=min(5, options.timeout)) as session:
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/basecommand.py", line 72, in _build_session
    insecure_hosts=options.trusted_hosts,
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/download.py", line 329, in __init__
    self.headers["User-Agent"] = user_agent()
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/download.py", line 93, in user_agent
    from pip._vendor import distro
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_vendor/distro.py", line 1050, in <module>
    _distro = LinuxDistribution()
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_vendor/distro.py", line 595, in __init__
    self._distro_release_info = self._get_distro_release_info()
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_vendor/distro.py", line 995, in _get_distro_release_info
    distro_info = self._parse_distro_release_file(filepath)
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/site-packages/pip/_vendor/distro.py", line 1018, in _parse_distro_release_file
    return self._parse_distro_release_content(fp.readline())
  File "/home/james/.pyenv/versions/3.6.0/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe7 in position 51: ordinal not in range(128)```

**Comment by Chrismarsh** [comment]
I also have this problem resulting in pip trying to install to a read-only system location
`ERROR: Could not install packages due to an EnvironmentError: [Errno 30] Read-only file system:`

**Comment by Chrismarsh** [comment]
Oh interesting, this seems to be related to having pyenv-which-ext installed. Without it, the pip shims are created, otherwise it seems to default to system pip.

**Comment by guyskk** [comment]
Maybe check the init script: `eval "$(pyenv init --path)"`, the `--path` seems new added in pyenv README.

**Comment by Chrismarsh** [comment]
Agreed that `--path` has perhaps cleaned up some of my issues (so far).
